### ISSUE TITLE
gc的位置是不是写错了

### ISSUE THREAD

**Issue by lanqsh** [Waleon/DesignPatterns#2]
static GC gc;写在了GC类内,是不是应该写在Singleton类内呢

**Comment by Waleon** [comment]
木有的

**Comment by lanqsh** [comment]
> 木有的

不好意思,之前没有编译就直接评论了,第一次看到类内定义自身实例的操作,没有想仔细导致我以为作者弄错了...
确实是可以的,我之前是定义内部类,静态成员定义在了Singleton,有点类似,所以想当然了,你这样写更高效
12     class Garbo
 13     {
 14     public:
 15         ~Garbo()
 16         {
 17             if(smInstance!=nullptr)
 18             {
 19                 cout << "~Garbo" << endl;
 20                 delete smInstance;
 21             }
 22         }
 23     };
 24 private:
 25     static Garbo smGarbo;
